<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<dict>
	<key>fileTypes</key>
	<array>
		<string>pmmusic</string>
	</array>
	<key>name</key>
	<string>PM music</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directives</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pmmusic</string>
	<key>uuid</key>
	<string>7fc37daa-2ce6-443b-9ec5-a1d20e40770f</string>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(//)(.*$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.line.double-slash.pmmusic</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>name</key>
					<string>comment.block.pmmusic</string>
					<key>end</key>
					<string>\*/</string>
				</dict>
			</array>
		</dict>
		<key>directives</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(INCLUDE|TITLE|COMPOSER|PROGRAMMER|DESCRIPTION|VARHEADER|OUTHEADER|OUTFILE)(?:[ \t](.*))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.$1.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.pmmusic</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.directive.$1.pmmusic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(OUTFORMAT)(?:[ \t](asm|c))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.$1.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.pmmusic</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.directive.$1.pmmusic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(M(?:ASTER)?TIME)(?:[ \t](?:(\d+)|((?:0x|\$)[\da-fA-F]+)))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.MASTERTIME.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.decimal.pmmusic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.hexadecimal.pmmusic</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.directive.MASTERTIME.pmmusic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(M(?:ASTER)?BPM)(?:[ \t](?:(\d+)|((?:0x|\$)[\da-fA-F]+))(?:,[ \t](?:(\d+)|((?:0x|\$)[\da-fA-F]+)))?)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.MASTERBPM.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.decimal.pmmusic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.hexadecimal.pmmusic</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.decimal.pmmusic</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.hexadecimal.pmmusic</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.directive.MASTERBPM.pmmusic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(VOLLVL|VOLLEVEL)(?:[ \t](mml|system))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.VOLLEVEL.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.pmmusic</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.directive.VOLLEVEL.pmmusic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(OCT(?:AVE)?REV)(?:[ \t](no|yes))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.OCTAVEREV.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.pmmusic</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.directive.OCTAVEREV.pmmusic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(SHORTQ(?:UANTIZE)?)(?:[ \t](no|yes))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.SHORTQUANTIZE.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.pmmusic</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.directive.SHORTQUANTIZE.pmmusic</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.block.bgm.pmmusic</string>
					<key>begin</key>
					<string>(BGM)[ \t]([^{ ]*)[ \t](\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.bgm.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.pmmusic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.begin.bracket.curly.pmmusic</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\|</string>
							<key>name</key>
							<string>punctuation.mark.loop.pmmusic</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[^\s{}|]+</string>
							<key>name</key>
							<string>entity.name.section.pmmusic</string>
						</dict>
					</array>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.end.bracket.curly.pmmusic</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.block.track.pattern.pmmusic</string>
					<key>begin</key>
					<string>(PAT(?:TERN)?_T(?:RACK)?)[ \t]([^{ ]*)[ \t](\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.track.pattern.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.pmmusic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.begin.bracket.curly.pmmusic</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#track-data</string>
						</dict>
					</array>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.end.bracket.curly.pmmusic</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.block.track.sfx.pmmusic</string>
					<key>begin</key>
					<string>(SFX_T(?:RACK)?)[ \t]([^{ ]*)[ \t](\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.track.sfx.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.pmmusic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.begin.bracket.curly.pmmusic</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#track-data</string>
						</dict>
					</array>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.end.bracket.curly.pmmusic</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.block.track.macro.pmmusic</string>
					<key>begin</key>
					<string>(MACRO_T(?:RACK)?)[ \t]([^{ ]*)[ \t](\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.track.macro.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.pmmusic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.begin.bracket.curly.pmmusic</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#track-data</string>
						</dict>
					</array>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.end.bracket.curly.pmmusic</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.block.pattern.pmmusic</string>
					<key>begin</key>
					<string>(PAT(?:TERN)?)[ \t]([^{ ]*)[ \t](\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.pattern.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.pmmusic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.begin.bracket.curly.pmmusic</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#mml-data</string>
						</dict>
					</array>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.end.bracket.curly.pmmusic</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.block.sfx.pmmusic</string>
					<key>begin</key>
					<string>(SFX)[ \t]([^{ ]*)[ \t](\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.sfx.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.pmmusic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.begin.bracket.curly.pmmusic</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#mml-data</string>
						</dict>
					</array>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.end.bracket.curly.pmmusic</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.block.macro.pmmusic</string>
					<key>begin</key>
					<string>(MACRO)[ \t]([^{ ]*)[ \t](\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.macro.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.pmmusic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.begin.bracket.curly.pmmusic</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#mml-data</string>
						</dict>
					</array>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.end.bracket.curly.pmmusic</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>track-data</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(ROW)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.track.row.pmmusic</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>match</key>
							<string>([A-G][-+#]?)([1-9])</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.language.pmmusic</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.integer.decimal.octave.pmmusic</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.mark.sound.note.pmmusic</string>
						</dict>
						<dict>
							<key>match</key>
							<string>([%vwqs]|x[tpsr])(?:(\d+)|((?:0x|\$)[\da-fA-F]+))</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.built-in.pmmusic</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.integer.decimal.pmmusic</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.integer.hexadecimal.pmmusic</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.mark.sound.modifier.pmmusic</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(xd)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.built-in.pmmusic</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.mark.sound.modifier.pmmusic</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(!|xa)(?:(\d+)|((?:0x|\$)[\da-fA-F]+)):(?:(\d+)|((?:0x|\$)[\da-fA-F]+))</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.built-in.pmmusic</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.integer.decimal.pmmusic</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.integer.hexadecimal.pmmusic</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.integer.decimal.pmmusic</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.integer.hexadecimal.pmmusic</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.mark.sound.modifier.pmmusic</string>
						</dict>
					</array>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.directive.row.pmmusic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.track.end.pmmusic</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.directive.end.pmmusic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(LOOP|MARK|DO)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.track.loop.begin.pmmusic</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.directive.loop.pmmusic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(ENDL(?:OOP)?|REPEAT) (?:(\d+)|((?:0x|\$)[\da-fA-F]+))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.track.loop.end.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.decimal.pmmusic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.hexadecimal.pmmusic</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.directive.endloop.pmmusic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(MACRO) ([A-Z])</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.track.macro.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.pmmusic</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.directive.macro.pmmusic</string>
				</dict>
			</array>
		</dict>
		<key>mml-data</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([a-g][-+#]?|r)([1-9]|\.\.?)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.language.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.decimal.length.pmmusic</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.mark.sound.note.pmmusic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([%\\/vwloqs]|x[tpsr])(?:(\d+)|((?:0x|\$)[\da-fA-F]+))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.built-in.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.decimal.pmmusic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.hexadecimal.pmmusic</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.mark.sound.modifier.pmmusic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(xd)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.built-in.pmmusic</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.mark.sound.modifier.pmmusic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(!|xa)(?:(\d+)|((?:0x|\$)[\da-fA-F]+)):(?:(\d+)|((?:0x|\$)[\da-fA-F]+))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.built-in.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.decimal.pmmusic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.hexadecimal.pmmusic</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.decimal.pmmusic</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.hexadecimal.pmmusic</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.mark.sound.modifier.pmmusic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>keyword.control.end.pmmusic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\[</string>
					<key>name</key>
					<string>keyword.control.loop.begin.pmmusic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\])(?:(\d+)|((?:0x|\$)[\da-fA-F]+))?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.loop.end.pmmusic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.decimal.pmmusic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.hexadecimal.pmmusic</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.endloop.pmmusic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[A-Z]</string>
					<key>name</key>
					<string>variable.other.pmmusic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;|&gt;</string>
					<key>name</key>
					<string>keyword.control.octave.step.pmmusic</string>
				</dict>
			</array>
		</dict>
	</dict>
</dict>
</plist>
